### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/Feather.jl#1]
The sources for `libfeather`, a C++ library to read, write and extract the metadata from feather files, are provided in the [feather repository](http://github.com/wesm/feather).  Both the `R` and `Python` packages, available in the same repository, use `libfeather` and wrappers.

The first decision in designing a Julia package is whether to use `libfeather`, either through wrappers or through [Cxx](https://github.com/keno/Cxx.jl), or to write a native Julia package that reads and writes the files directly.

Obviously it would be faster to get a package running using wrappers about the `libfeather` classes and methods.  It would also be safer in that the definition of the format is essentially "whatever is implemented in libfeather".  That library itself uses [FlatBuffers](https://google.github.io/flatbuffers/) to verify and decode the metadata in a feather file, which provides another level of safety.

Let me propose several approaches

- level 0: (already done) use [RCall](https://github.com/JuliaStats/RCall.jl) and the R `feather` package

```julia
julia> using RCall

julia> mtcars = R""" library(feather); read_feather(feather_example("mtcars.feather")) """ |> rcopy
32x11 DataFrames.DataFrame
│ Row │ mpg  │ cyl │ disp  │ hp    │ drat │ wt    │ qsec  │ vs  │ am  │ gear │ carb │
┝━━━━━┿━━━━━━┿━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━┿━━━━━┿━━━━━━┿━━━━━━┥
│ 1   │ 21.0 │ 6.0 │ 160.0 │ 110.0 │ 3.9  │ 2.62  │ 16.46 │ 0.0 │ 1.0 │ 4.0  │ 4.0  │
│ 2   │ 21.0 │ 6.0 │ 160.0 │ 110.0 │ 3.9  │ 2.875 │ 17.02 │ 0.0 │ 1.0 │ 4.0  │ 4.0  │
│ 3   │ 22.8 │ 4.0 │ 108.0 │ 93.0  │ 3.85 │ 2.32  │ 18.61 │ 1.0 │ 1.0 │ 4.0  │ 1.0  │
│ 4   │ 21.4 │ 6.0 │ 258.0 │ 110.0 │ 3.08 │ 3.215 │ 19.44 │ 1.0 │ 0.0 │ 3.0  │ 1.0  │
│ 5   │ 18.7 │ 8.0 │ 360.0 │ 175.0 │ 3.15 │ 3.44  │ 17.02 │ 0.0 │ 0.0 │ 3.0  │ 2.0  │
│ 6   │ 18.1 │ 6.0 │ 225.0 │ 105.0 │ 2.76 │ 3.46  │ 20.22 │ 1.0 │ 0.0 │ 3.0  │ 1.0  │
│ 7   │ 14.3 │ 8.0 │ 360.0 │ 245.0 │ 3.21 │ 3.57  │ 15.84 │ 0.0 │ 0.0 │ 3.0  │ 4.0  │
│ 8   │ 24.4 │ 4.0 │ 146.7 │ 62.0  │ 3.69 │ 3.19  │ 20.0  │ 1.0 │ 0.0 │ 4.0  │ 2.0  │
│ 9   │ 22.8 │ 4.0 │ 140.8 │ 95.0  │ 3.92 │ 3.15  │ 22.9  │ 1.0 │ 0.0 │ 4.0  │ 2.0  │
│ 10  │ 19.2 │ 6.0 │ 167.6 │ 123.0 │ 3.92 │ 3.44  │ 18.3  │ 1.0 │ 0.0 │ 4.0  │ 4.0  │
│ 11  │ 17.8 │ 6.0 │ 167.6 │ 123.0 │ 3.92 │ 3.44  │ 18.9  │ 1.0 │ 0.0 │ 4.0  │ 4.0  │
│ 12  │ 16.4 │ 8.0 │ 275.8 │ 180.0 │ 3.07 │ 4.07  │ 17.4  │ 0.0 │ 0.0 │ 3.0  │ 3.0  │
│ 13  │ 17.3 │ 8.0 │ 275.8 │ 180.0 │ 3.07 │ 3.73  │ 17.6  │ 0.0 │ 0.0 │ 3.0  │ 3.0  │
│ 14  │ 15.2 │ 8.0 │ 275.8 │ 180.0 │ 3.07 │ 3.78  │ 18.0  │ 0.0 │ 0.0 │ 3.0  │ 3.0  │
│ 15  │ 10.4 │ 8.0 │ 472.0 │ 205.0 │ 2.93 │ 5.25  │ 17.98 │ 0.0 │ 0.0 │ 3.0  │ 4.0  │
│ 16  │ 10.4 │ 8.0 │ 460.0 │ 215.0 │ 3.0  │ 5.424 │ 17.82 │ 0.0 │ 0.0 │ 3.0  │ 4.0  │
│ 17  │ 14.7 │ 8.0 │ 440.0 │ 230.0 │ 3.23 │ 5.345 │ 17.42 │ 0.0 │ 0.0 │ 3.0  │ 4.0  │
│ 18  │ 32.4 │ 4.0 │ 78.7  │ 66.0  │ 4.08 │ 2.2   │ 19.47 │ 1.0 │ 1.0 │ 4.0  │ 1.0  │
│ 19  │ 30.4 │ 4.0 │ 75.7  │ 52.0  │ 4.93 │ 1.615 │ 18.52 │ 1.0 │ 1.0 │ 4.0  │ 2.0  │
│ 20  │ 33.9 │ 4.0 │ 71.1  │ 65.0  │ 4.22 │ 1.835 │ 19.9  │ 1.0 │ 1.0 │ 4.0  │ 1.0  │
│ 21  │ 21.5 │ 4.0 │ 120.1 │ 97.0  │ 3.7  │ 2.465 │ 20.01 │ 1.0 │ 0.0 │ 3.0  │ 1.0  │
│ 22  │ 15.5 │ 8.0 │ 318.0 │ 150.0 │ 2.76 │ 3.52  │ 16.87 │ 0.0 │ 0.0 │ 3.0  │ 2.0  │
│ 23  │ 15.2 │ 8.0 │ 304.0 │ 150.0 │ 3.15 │ 3.435 │ 17.3  │ 0.0 │ 0.0 │ 3.0  │ 2.0  │
│ 24  │ 13.3 │ 8.0 │ 350.0 │ 245.0 │ 3.73 │ 3.84  │ 15.41 │ 0.0 │ 0.0 │ 3.0  │ 4.0  │
│ 25  │ 19.2 │ 8.0 │ 400.0 │ 175.0 │ 3.08 │ 3.845 │ 17.05 │ 0.0 │ 0.0 │ 3.0  │ 2.0  │
│ 26  │ 27.3 │ 4.0 │ 79.0  │ 66.0  │ 4.08 │ 1.935 │ 18.9  │ 1.0 │ 1.0 │ 4.0  │ 1.0  │
│ 27  │ 26.0 │ 4.0 │ 120.3 │ 91.0  │ 4.43 │ 2.14  │ 16.7  │ 0.0 │ 1.0 │ 5.0  │ 2.0  │
│ 28  │ 30.4 │ 4.0 │ 95.1  │ 113.0 │ 3.77 │ 1.513 │ 16.9  │ 1.0 │ 1.0 │ 5.0  │ 2.0  │
│ 29  │ 15.8 │ 8.0 │ 351.0 │ 264.0 │ 4.22 │ 3.17  │ 14.5  │ 0.0 │ 1.0 │ 5.0  │ 4.0  │
│ 30  │ 19.7 │ 6.0 │ 145.0 │ 175.0 │ 3.62 │ 2.77  │ 15.5  │ 0.0 │ 1.0 │ 5.0  │ 6.0  │
│ 31  │ 15.0 │ 8.0 │ 301.0 │ 335.0 │ 3.54 │ 3.57  │ 14.6  │ 0.0 │ 1.0 │ 5.0  │ 8.0  │
│ 32  │ 21.4 │ 4.0 │ 121.0 │ 109.0 │ 4.11 │ 2.78  │ 18.6  │ 1.0 │ 1.0 │ 4.0  │ 2.0  │
```

Disadvantages: reading and writing feather files will need to go through R which allows for fewer data types than either Julia or the feather format.  Information will be lost or file size will be larger than needed. Also, the data will always end up being copied at least once and possibly several times.

- level 1: Use [PyCall](https://github.com/stevengj/Pycall.jl) and the feather package for Python

My Python is pretty rusty and I haven't been able to install the Python package to check this out.  I hope that someone with more experience in Python and pandas, e.g. @stevengj or @johnmyleswhite, can check this out.

- level 2: Write wrappers around libfeather classes and methods so they can be called via `ccall`

Disadvantage: the need to use BinDeps to download and install libfeather and to compile the wrapper code.

- level 3: Use [Cxx](https://github.com/keno/Cxx.jl) and libfeather

Disadvantage: Cxx has not yet officially been released.  It easy to use if your name is Keno - others may encounter some difficulty  The interface exposed by Cxx is, in my experience, less sophisticated than may be necessary to work with classes in libfeather.  Again, not a problem if your name is Keno. 

Conclusion: Doable but perhaps fragile for the next several months.  It would require a pretty deep dive into Cxx, I think.

- level 4: Write a native Julia interface, perhaps using a wrapper around Flatbuffers.

Advantages: For reading and extracting metadata the file can be memory-mapped as a `UInt8` vector.  I believe that `reinterpret` can be used on the primitive types (bitstypes in Julia) to memory-map the columns.

Disadvantage: Would require an extensive test suite to make sure that corner cases are covered.  Would take much more effort to write but, ultimately, could be easier to maintain.

I am going to ping several developers who may not otherwise read this issue in hopes that they will comment or offer suggestions.  @wesm and @hadley are the developers of libfeather and the Python and R packages.  @timholy who wrote the [HDF5](https://github.com/timholy/HDF5.jl) package, @keno who wrote the Cxx package.

**Comment by wesm** [comment]
This is great -- I will have to look more closely when it is not the middle of Strata.

Aside: From an organizational perspective I am curious if there would be any benefits to creating a single Feather GitHub project? We could ask https://github.com/feather if he would be willing to give us the Feather organization

**Comment by wesm** [comment]
For Julia my inclination would be to create a C99 wrapper API for the C++ library (similar to how Snappy is made callable for C libraries, although snappy has a less complex API) if that is feasible.

**Comment by dmbates** [comment]
I wrote a bit of C++ code in the `deps/src` directory and can get to the point of opening a feather file and checking on some of the metadata.  I'm going to need to look into either holding onto a pointer (i.e. I need to read about `std::shared_ptr` and `std::unique_ptr`) to see if I can preserve the open table while setting up structures at the Julia level or find how to create Julia vectors in C/C++ code.

As a temporary measure I could open the table to get the number of rows and columns then open it again after allocating the storage for the results.

**Comment by dmbates** [comment]
Well, I'm about to give up.  

I can't do level 3 (using [Cxx](https://github.com/keno/Cxx.jl) ) because Cxx reliably segfaults for me right now.

I don't have the energy to do level 4 (write a native implementation in Julia) because there is no documentation for the format per se.  I can guess a bit but the structure of the metadata table is a bit opaque and the actual code that defines it is one level removed in Flatbuffers.

@wesm suggested writing a C99 wrapper API for the C++ library but my attempts to do so have not met with great success.  So many important objects are passed around as `std::unique_ptr<feather::whatever>` or `std::shared_ptr<feather::whatever>` which I don't know have to convert to something accessible through C.  More importantly, I don't know when a destructor will be invoked on these objects.

I guess we'll need to stick to level 0 until someone with an interest and better C++ skills than I comes along.

**Comment by wesm** [comment]
Writing a C API is almost certainly the best route, but as you say we may need to make some changes to the C++ interface to make this easier. I'll try to have a look when I can.

Aside: It would be great if we could collaborate on Feather in one place on GitHub, especially if there are patches which affect multiple language bindings at once. let me know if you have ideas

**Comment by wesm** [comment]
Here is very honestly what I would hope to see:

https://github.com/apache/avro/tree/master/lang

**Comment by tshort** [comment]
@dmbates, [CxxWrap.jl](https://github.com/barche/CxxWrap.jl) is another option you might want to look at. You might be able to use the feather [Rcpp code](https://github.com/wesm/feather/tree/master/R/src) as a starting point.

**Comment by tkelman** [comment]
@wesm in terms of the way the Julia package manager works, the Julia bindings are best located in a repo with roughly the structure that this one currently has. You could play git tricks with symlinks or submodules or a script that auto-populates one repository from the other? All somewhat messy.

**Comment by wesm** [comment]
Seems like an unconvincing design, but good to know, anyway. Thanks

**Comment by tkelman** [comment]
The installed artifact *is* the git repository, for better or worse. Structural flexibility hasn't been implemented yet.

**Comment by wesm** [comment]
If the C API I assembled in wesm/feather#96 works for you all, I can merge that patch and add the missing Feather C++ functionality (category types, date/time types)

**Comment by dmbates** [comment]
@wesm Thanks for adding the C API, which I have used successfully.
