### ISSUE TITLE
Use a specific docker tag for running the round-trip tests

### ISSUE THREAD

**Issue by tkelman** [JuliaStats/Feather.jl#17]
https://github.com/JuliaStats/Feather.jl/blob/703485656607a7ceeff9c88ec385a943c37847c0/test/runtests.jl#L107 - otherwise you're pulling from latest, which isn't good for reproducibility of past test results.

**Comment by tkelman** [comment]
If you've pulled multiple tags, I think run without a tag specification will run the newest that has been pulled.

**Comment by quinnj** [comment]
Good point, just pushed a fix.
