### ISSUE TITLE
Data.getcolumn is still used

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/Feather.jl#24]
[This](https://github.com/JuliaStats/Feather.jl/blob/master/src/Feather.jl#L132) line here still uses ``Data.getcolumn``, but that seems no longer supported. Query's tests error out with that right now on the branch that tries to keep track with all the new updates.

**Comment by davidanthoff** [comment]
Also, shouldn't this kind of thing be caught by travis?

**Comment by quinnj** [comment]
Sorry about that. Fixed via 6977a078cc02cb19ae92b42d01f75589bfe2dfd3. I'm trying to sort out a better overall testing framework right now to keep each package's tests manageable but still have some solid integration tests. See here for WIP: https://github.com/JuliaData/DataStreamsIntegrationTests.

We definitely still need to test all our code paths in our own runtests though.

**Comment by davidanthoff** [comment]
@quinnj Could you tag a new version that has this fix? Right now [Query.jl](https://github.com/davidanthoff/Query.jl) is broken because of this bug, so it would be good if there was a tagged version that has this fixed.
