### ISSUE TITLE
bizarre `DataFrames` issue causes a conversion failure sometimes

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaStats/Feather.jl#25]
Ok, here is a strange problem that is largely the fault of the `DataFrames` package but it almost surely needs to be addressed here as well.

When attempting to serialize a `DataFrame` one gets the following error:
```
ERROR: LoadError: MethodError: no method matching values(::DataArrays.DataArray{Float64,1})
Closest candidates are:
  values(::Array{T,1}) at /home/savastio/.julia/v0.5/Feather/src/Feather.jl:265
  values(::NullableArrays.NullableArray{T,1}) at /home/savastio/.julia/v0.5/Feather/src/Feather.jl:268
  values{S,R}(::Union{CategoricalArrays.CategoricalArray{S,1,R},CategoricalArrays.NullableCategoricalArray{S,1,R}}) at /home/savastio/.julia/v0.5/Feather/src/Feather.jl:269
 in writecolumn(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Type{Float64}, ::DataArrays.DataArray{Float64,1}) at /home/savastio/.julia/v0.5/Feather/src/Feather.jl:297
 in close!(::Feather.Sink) at /home/savastio/.julia/v0.5/Feather/src/Feather.jl:407
 in #write#26(::Bool, ::Dict{Int64,Function}, ::Array{Any,1}, ::Function, ::String, ::DataFrames.DataFrame) at /home/savastio/.julia/v0.5/Feather/src/Feather.jl:454
 in write(::String, ::DataFrames.DataFrame) at /home/savastio/.julia/v0.5/Feather/src/Feather.jl:453
 in include_from_node1(::String) at ./loading.jl:488
while loading /home/savastio/src/feather_performance.jl, in expression starting on line 184
```

What's particularly bizarre about this is that whether or not one gets this error depends on how the `DataFrame` was constructed.  Apparently, if one constructs the `DataFrame` directly from an array using something like `DataFrame(A)` then the `DataFrame` column is a `Vector`.  However, if one constructs the `DataFrame` in any other way such as by assigning individual columns (i.e. `DataFrame(A=A, B=B)`) then the columns are `DataArray`s.  Clearly this is a fault with `DataFrames` and it should be changed so that these objects are always `DataArray`s.  I wanted to see what people thought about the issue here before I opened one on `DataFrames`.

Anyway, certainly `Feather` should support both cases.  Adding the method
```julia
values(A::DataArray) = convert(Vector, A)
```
to Feather.jl seems to completely fix the problem, but this doesn't address cases when there are `NA`s.  Since there isn't a canonical binary representation of `NA` so it wouldn't be unreasonable to throw an error if there are `NA`s.  Actually, with the change I suggested above it throws a rather appropriate `LoadError` saying that it can't convert `DataArray` with `NA` to the desired type, so maybe nothing further needs to be done.

**Comment by quinnj** [comment]
Thanks for the report. I forgot to go back and test that we still support DataFrames with DataArray columns. Should be fixed on master now.

**Comment by ExpandingMan** [comment]
Thanks, one thing: if there are `NA`s in the `DataFrame` wouldn't what you did return bogus or undefined values instead of throwing a `LoadError`?  (because I believe the spots with `NA`s are undefined in `A.data`)

**Comment by quinnj** [comment]
No, the null values are encoded separately from the values. In particular, part of what I just added is [this line](https://github.com/JuliaStats/Feather.jl/commit/6977a078cc02cb19ae92b42d01f75589bfe2dfd3#diff-473d205019ce6eab63c58e026455b95cR356) which makes sure the nulls are encoded correctly for DataArrays.

**Comment by ExpandingMan** [comment]
Ah, didn't see that, ok thanks.
