### ISSUE TITLE
python feather reads back wrong datetimes

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaStats/Feather.jl#28]
Feather files containing `DateTime` columns written with this package are read incorrectly when loaded using `feather.read_dataframe` in python.  I suspect this is a precision issue of some sort: Julia `DateTime`s display to the nearest millisecond while `numpy` timestamps display (by default) to the nearest nanosecond.  

Here are a couple examples:

"2016-10-05T12:56:30.127" is read as
"1970-01-01 00:24:35.672190127" in python

"2016-10-06T12:56:30.181" is read as
"1970-01-01 00:24:35.758590181" in python

**Comment by quinnj** [comment]
This is a python issue, not julia. https://github.com/wesm/feather/issues/194

**Comment by ExpandingMan** [comment]
Ah, got it, thanks.
