### ISSUE TITLE
Feather.write not working for the simplest scenario ?

### ISSUE THREAD

**Issue by em7b5** [JuliaStats/Feather.jl#29]
Hello.  Can someone please tell me what I am doing wrong here?  Feather.write throws MethodError regarding Int64.  I have tried Feather.write with other dataframe instances as well; I get the same error.  E.g., df =  Feather.read("BOD.feather") from the Feather\test\data directory works fine, but Feather.write for this df throws the same error.

Pkg.update(), Pkg.status(), versioninfo() were executed before trying this; results of these calls were moved below the error dump.

julia> using DataFrames

julia> using Feather

julia> df = DataFrame(x1=[1, 2], x2=["foo", "bar"])
2x2 DataFrames.DataFrame
│ Row │ x1 │ x2    │
├─────┼────┼───────┤
│ 1   │ 1  │ "foo" │
│ 2   │ 2  │ "bar" │

julia> Feather.write("test.feather", df)
ERROR: MethodError: no method matching values(::DataArrays.DataArray{Int64,1})
Closest candidates are:
  values(::Array{T,1}) at C:\Users\inewton\.julia\v0.5\Feather\src\Feather.jl:26
5
  values(::NullableArrays.NullableArray{T,1}) at C:\Users\inewton\.julia\v0.5\Fe
ather\src\Feather.jl:266
  values{S,R}(::Union{CategoricalArrays.CategoricalArray{S,1,R},CategoricalArray
s.NullableCategoricalArray{S,1,R}}) at C:\Users\inewton\.julia\v0.5\Feather\src\
Feather.jl:267
 in writecolumn(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Type{Int64}, ::DataAr
rays.DataArray{Int64,1}) at C:\Users\inewton\.julia\v0.5\Feather\src\Feather.jl:
295
 in close!(::Feather.Sink) at C:\Users\inewton\.julia\v0.5\Feather\src\Feather.j
l:405
 in #write#26(::Bool, ::Dict{Int64,Function}, ::Array{Any,1}, ::Function, ::Stri
ng, ::DataFrames.DataFrame) at C:\Users\inewton\.julia\v0.5\Feather\src\Feather.
jl:452
 in write(::String, ::DataFrames.DataFrame) at C:\Users\inewton\.julia\v0.5\Feat
her\src\Feather.jl:451

I ran this BEFORE executing the above code:

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of DataFrames...
INFO: Updating cache of DataFrames...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.status()
4 required packages:
 - Atom                          0.5.4
 - DataFrames                    0.8.3
 - Feather                       0.2.0
 - IJulia                        1.3.2
59 additional packages:
 - ASTInterpreter                0.0.4
 - AbstractTrees                 0.0.4
 - ArgParse                      0.3.1
 - BinDeps                       0.4.5
 - Blink                         0.4.2
 - BufferedStreams               0.2.0
 - COFF                          0.0.2
 - CRC                           1.2.0
 - CategoricalArrays             0.0.6
 - CodeTools                     0.4.2
 - Codecs                        0.2.0
 - ColorTypes                    0.2.8
 - Colors                        0.6.8
 - Compat                        0.9.2
 - Conda                         0.3.2
 - DWARF                         0.1.0
 - DataArrays                    0.3.8
 - DataStreams                   0.1.0
 - ELF                           0.1.0
 - FileIO                        0.2.0
 - FixedPointNumbers             0.1.8
 - FlatBuffers                   0.1.2
 - GZip                          0.2.20
 - Gallium                       0.0.4
 - Hiccup                        0.0.3
 - HttpCommon                    0.2.6
 - HttpParser                    0.2.0
 - HttpServer                    0.1.7
 - JSON                          0.8.0
 - JuliaParser                   0.7.4
 - Juno                          0.2.3
 - LNR                           0.0.2
 - Lazy                          0.11.4
 - LegacyStrings                 0.1.1
 - LibExpat                      0.2.1
 - Libz                          0.2.0
 - MachO                         0.0.4
 - MacroTools                    0.3.2
 - MbedTLS                       0.3.0
 - Media                         0.2.3
 - Mustache                      0.1.2
 - Mux                           0.2.2
 - Nettle                        0.2.4
 - NullableArrays                0.0.9
 - ObjFileBase                   0.0.4
 - Reactive                      0.3.5
 - Reexport                      0.0.3
 - SHA                           0.2.1
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.10.0
 - StructIO                      0.0.2
 - TerminalUI                    0.0.2
 - TextWrap                      0.1.6
 - URIParser                     0.1.6
 - VT100                         0.0.2
 - WeakRefStrings                0.2.0
 - WebSockets                    0.2.1
 - WinRPM                        0.2.1
 - ZMQ                           0.3.4

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

**Comment by ExpandingMan** [comment]
This is the same issue I experienced [#25](https://github.com/JuliaStats/Feather.jl/issues/25).  It's due to the rather bizarre fact that the type of `DataFrame` columns depends on how the `DataFrame` is declared.  If you pull from master using `Pkg.checkout("Feather")` you'll find the problem is fixed.

**Comment by em7b5** [comment]
Thank you sir! Pkg.checkout("Feather") worked. I hate re-asking a resolved question, but I am new enough to Julia and GitHub that issue #25, even though I read it prior to posting, had no traction for me.
