### ISSUE TITLE
Error on x86 on Windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/Feather.jl#32]
Here is the repo code:

``` julia
using DataFrames, Feather

Feather.write("repo2.feather",DataFrame(a=["a","b","c"]))

Feather.read("repo2.feather")
```

I get the following error:

```
ERROR: MethodError: no method matching WeakRefStrings.WeakRefString{T}(::Ptr{UInt8}, ::Int32, ::Int64)
Closest candidates are:
  WeakRefStrings.WeakRefString{T}{T}(::Ptr{T}, ::Int32, ::Int32) at C:\Users\anthoff\.julia\v0.5\WeakRefStrings\src\WeakRefStrings.jl:24
  WeakRefStrings.WeakRefString{T}{T}(::Ptr{T}, ::Any) at C:\Users\anthoff\.julia\v0.5\WeakRefStrings\src\WeakRefStrings.jl:29
  WeakRefStrings.WeakRefString{T}{T}(::Any) at sysimg.jl:53
 in (::Feather.##16#17{Feather.Source,Array{Int32,1},Int64})(::Int64) at .\<missing>:0
 in collect(::Base.Generator{UnitRange{Int64},Feather.##16#17{Feather.Source,Array{Int32,1},Int64}}) at .\array.jl:307
 in streamfrom(::Feather.Source, ::Type{DataStreams.Data.Column}, ::Type{NullableArrays.NullableArray{WeakRefString{UInt8},1}}, ::Int32) at C:\Users\anthoff\.julia\v0.5\Feather\src\Feather.jl:181
 in streamto!(::DataFrames.DataFrame, ::Type{DataStreams.Data.Column}, ::Feather.Source, ::Type{NullableArrays.NullableArray{WeakRefString{UInt8},1}}, ::Type{NullableArrays.NullableArray{WeakRefString{UInt8},1}}, ::Int32, ::Int32, ::DataStreams.Data.Schema{true}, ::Base.#identity) at C:\Users\anthoff\.julia\v0.5\DataStreams\src\DataStreams.jl:216
 in stream!(::Feather.Source, ::Type{DataStreams.Data.Column}, ::DataFrames.DataFrame, ::DataStreams.Data.Schema{true}, ::DataStreams.Data.Schema{true}, ::Array{Function,1}) at C:\Users\anthoff\.julia\v0.5\DataStreams\src\DataStreams.jl:229
 in #stream!#5(::Array{Any,1}, ::Function, ::Feather.Source, ::Type{DataFrames.DataFrame}, ::Bool, ::Dict{Int32,Function}) at C:\Users\anthoff\.julia\v0.5\DataStreams\src\DataStreams.jl:149
 in #read#19 at C:\Users\anthoff\.julia\v0.5\Feather\src\Feather.jl:235 [inlined]
 in read(::String, ::Type{DataFrames.DataFrame}) at C:\Users\anthoff\.julia\v0.5\Feather\src\Feather.jl:235
 in read(::String) at C:\Users\anthoff\.julia\v0.5\Feather\src\Feather.jl:229
```

**Comment by quinnj** [comment]
I don't think this is an issue any more, right @davidanthoff?

**Comment by davidanthoff** [comment]
Still there, I get the same error both on the latest tagged version of ``Feather`` and on ``master``.

**Comment by quinnj** [comment]
Ah, great to know and sorry for the delay on checking in on this. I'll try and debug this tonight when I can get back to a windows machine. I also noticed that I somehow never turned appveyor on for this repo. I've turned it on now and started a build, so we'll see if that gives some more info too.

**Comment by davidanthoff** [comment]
Bump, any progress on this? I want to tag a new version of Query that supports DataTables, but this error here makes the CI tests fail.

**Comment by quinnj** [comment]
Sorry for the slowness here; do give the fix a try.

**Comment by davidanthoff** [comment]
I don't think that fixed it, the corresponding [appveyor build](https://ci.appveyor.com/project/quinnj/feather-jl/build/1.0.8/job/yh0hojjgd9malcg6) still shows the same error.

**Comment by quinnj** [comment]
Oops, the most recent commit seems to have fixed it. I'll be working on 0.6-readiness in the coming week or so.

**Comment by davidanthoff** [comment]
Cool, thanks! Would be great if you could tag a version that has this fix so that my CI builds pick that up.

**Comment by tkelman** [comment]
Is this a Windows problem or a 32 bit problem? Not much of a fix to stop running the tests.

**Comment by davidanthoff** [comment]
I think it was a 32 bit problem, and it seems to me that [this](https://github.com/JuliaStats/Feather.jl/commit/18b7c297c331d6cd960af082d772e4c35834f796) properly fixed it?

**Comment by tkelman** [comment]
likely, so worth removing the `is_windows` check from https://github.com/JuliaStats/Feather.jl/commit/151be3084d58cb1efa99a841c16b1880420f9ea1

**Comment by quinnj** [comment]
This issue specifically was about 32-bit, which was fixed. In terms of running the tests, we're currently running into issues w/ DataStreamsIntegrationTests and the fact that it tries to `rm` the files. I have some other ideas on how to make this work, but I think it's fine to disable the tests for now.

**Comment by tkelman** [comment]
close file handles sooner

**Comment by quinnj** [comment]
It's a non-trivial change to DataStreamsIntegrationTests, hence the temporary punt.
