### ISSUE TITLE
Converting from NullableWeakRefString to String

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaStats/Feather.jl#33]
I found this package yesterday and think it is great. When reading a feather file generated by pandas, the string columns come out as `Nullable{WeakRefString{UInt8}}` is there a "right way" to convert this to a DataFrame with regular Strings for this Column? I dropped the Nulls before writing the feather file, so I know there will be no nulls in the feather file.

**Comment by quinnj** [comment]
Yes, you can `Feather.read(file; weakrefstrings=false)` to ensure regular `String`s are generated.

**Comment by jpfairbanks** [comment]
Thanks
