### ISSUE TITLE
Appveyor badge points to wrong project

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/Feather.jl#37]
I think the link just needs to be adjusted to point to the feather appveyor build.

**Comment by ararslan** [comment]
What's an AppVeyor bag?

**Comment by davidanthoff** [comment]
Sorry, typo, I meant to status badge.

**Comment by ararslan** [comment]
Ohhhh haha that makes more sense. Thanks for the report.

**Comment by quinnj** [comment]
Fixed.
