### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/Feather.jl#5]
Many thanks to @barche for helping me with using [`CxxWrap`](https://github.com/barche/CxxWrap.jl/commit/e22cee6e2ccfbe4072f4061465a0cf459c16d9fb)  I saw the mention of your recent presentation about the package at https://twitter.com/MandelKen/status/720247980188659712

In the end I did the typical geek thing of "Why don't I write a native Julia implementation of [flatbuffers](https://google.github.io/flatbuffers) instead of messing with this C++ library?  I mean, how hard can it be?"  The metadata in a feather file is expressed using a flatbuffers schema.  Once I can extract the metadata the other parts of reading a feather file are straightforward.

It turns out that it wasn't that hard after all.  So much of the work in the C++ library is because you are trying to express dynamic types in a statically-typed language.

I should have an initial commit of the FlatBuffers.jl package later today.

**Comment by jpfairbanks** [comment]
This is really cool. A new C++ library comes out and it gets wrapped in 2 weeks. Then we will get a native julia solution showing both the great C/C++ interop capabilities and the power of julia itself. :+1: 

I just thought I would say something nice on the internet today :smile:

**Comment by barche** [comment]
Aha, thanks, I was blissfully unaware of that tweet :)

I completely agree that going pure Julia is the best way forward. The experiment benefited CxxWrap anyhow, since we now have support for smart pointers, an issue that would have come up sooner or later anyway.

**Comment by dmbates** [comment]
Change over is ecee6bbb3598b9db6d362a4d554843565c05c143.  Still needs a bit of work because I changed the organization of [FlatBuffers.jl](https://github.com/dmbates/FlatBuffers.jl) while writing its documentation.
