### ISSUE TITLE
DataArrays to DataFrame

### ISSUE THREAD

**Issue by minyoung89** [JuliaStats/Feather.jl#52]
I have DataArrays file which looks like this:
df
594482×12 DataArrays.DataArray{Int64,2}:
 1     NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
 0    0    0    1    NA  NA  NA  NA  NA  NA  NA  NA
 0    1     NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
 1     NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
 1     NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
 0    0    1     NA  NA  NA  NA  NA  NA  NA  NA  NA
 0    1     NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
 0    1     NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
 ⋮                       ⋮                   ⋮     
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA
  NA   NA   NA   NA  NA  NA  NA  NA  NA  NA  NA  NA

I am trying to convert this to DataFrame file, so I could writetable as .csv file.

When I do DataFrame(df), the followin error messages pop up:

MethodError: Cannot `convert` an object of type DataArrays.DataArray{Int64,2} to an object of type DataFrames.DataFrame

How could I convert a DataArrays array with dimension 2 (matrix) into DataFrame?

**Comment by ararslan** [comment]
Hey @minyoung89. We use the issue tracker for bug reports and feature requests. For general questions such as this, we recommend posting to [Discourse](https://discourse.julialang.org). (Also note that you've submitted an issue on the Feather package, which is unrelated to your question.)
