### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/Feather.jl#8]
@quinnj I have been unable to get `Flatbuffers` or `Feather` to pass tests and I have been struggling with this all day.  For myself, I am going back to the `dmb/dxx` branch because that actually can be used to read feather files.

**Comment by andreasnoack** [comment]
Maybe this is the issue?

**Comment by dmbates** [comment]
@andreasnoack I don't think the `julia 0.5` is the issue  (even thought that should be fixed).  For me it will install on v0.5-dev but with a warning.  I will make the change and see if that helps at all.

**Comment by quinnj** [comment]
Hey @dmbates, sorry for the hassle. Unfortunately, we've been hit by https://github.com/JuliaLang/julia/pull/16852 where `pointer_to_array` was incorrectly deprecated. There's also a compat fix on the way for the new `unsafe_wrapper(Array, ptr)`, so we'll incorporate that. As I mentioned, the Feather PR was not as polished as the FlatBuffers, I'll try to clean things right away.

**Comment by quinnj** [comment]
You'll also need to do `Pkg.clone("https://github.com/quinnj/Arrow.jl")` to get the `Arrow` package.

**Comment by quinnj** [comment]
Ok, so FlatBuffers should now be totally clean on 0.4/0.5. Feather is now working on 0.5, and I'm working on 0.4.

**Comment by quinnj** [comment]
Ok, both packages should be clear on 0.4 and 0.5 now.

**Comment by tshort** [comment]
REQUIRE needs to be switched back for Julia v0.4.

**Comment by quinnj** [comment]
Updated.
